steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/{billskoda/gcp-cd-codelab"]
    env: ["PROJECT_ROOT=github.com/{billskoda}/gcp-cd-codelab"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/{gcp-cd-codelab-id1001}/gcp-cd-codelab:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/{gcp-cd-codelab-id1001}/gcp-cd-codelab:$REVISION_ID"
